# Generated by Django 4.1.7 on 2023-03-12 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Industrio', max_length=255)),
                ('email', models.EmailField(default='Industrio@Industrio.com', max_length=254, null=True)),
                ('phone', models.CharField(default='966563315019', max_length=255)),
                ('facebook_link', models.URLField(null=True)),
                ('instagram_link', models.URLField(null=True)),
                ('linkendin_link', models.URLField(null=True)),
                ('youtube_link', models.URLField(null=True)),
                ('address', models.TextField(null=True)),
            ],
            options={
                'verbose_name': 'Websitre Info',
            },
        ),
    ]
