# Generated by Django 4.1.7 on 2023-03-14 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0003_project"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="projects_images/"
            ),
        ),
    ]
